spring:
  datasource:
    url: jdbc:h2:mem:pricingdb-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  sql:
    init:
      mode: always
