spring:
  application:
    name: inditex-prices
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # Desactivar la generación automática de Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always # Siempre ejecutar scripts de inicialización
      platform: h2 # Especificar la plataforma para los scripts

server:
  port: 8080

logging:
  level:
    com.inditex: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE